checkout/urls.py
from django.urls import path 
from . views import checkout, payment, charge, oderView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('payment/', payment, name="payment"),
	path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from products.views import (
    indexView,
    postFriend, 
    checkNickName,
)

urlpatterns = [
 	path('', include('products.urls', namespace='mainapp')),
 	path('', include('checkout.urls', namespace='checkout')),
    # path('product_detail.html',indexView),
    # path('product/br/',indexView),
    path('post/ajax/friend', postFriend, name = "post_friend"),
    path('get/ajax/validate/nickname', checkNickName, name = "validate_nickname"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('index11.html',indexView),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart
from . views import home, ProductDetail, Home, postFriend, checkNickName,indexView
app_name= 'mainapp'

urlpatterns = [

    path('', home, name='home'),
    path('p', Home.as_view(), name='home'),
    path('product/<slug>/', indexView, name='product'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
  
]

products/models.py
from django.db import models
from django.urls import reverse

# Category Model
class Category(models.Model):
    title = models.CharField(max_length=300)
    primaryCategory = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

#Product Model
class  Product(models.Model):

   
    mainimage = models.ImageField(upload_to='products/', blank=True)
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = models.FloatField()
    

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("mainapp:product", kwargs={
            'slug': self.slug
        })

    def result (self):
        res = friend.tirazh 
        return res

class Option(models.Model):

   
    mainimage = models.ImageField(upload_to='products/', blank=True)
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("mainapp:product", kwargs={
            'slug': self.slug
        })



        
class Friend(models.Model):


    first_name = models.CharField(max_length=100)
    tirazh = models.IntegerField(null=False)
    dob = models.DateField(auto_now=False, auto_now_add=False)
  


   
    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(Friend, self).save(*args, **kwargs)
 
    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()
    
    
   

products/forms.py
from .models import Friend
from django import forms
import datetime

# class FriendForm(forms.ModelForm):
#     ## change the widget of the date field.
#     dob = forms.DateField(
#         label='What is your birth date?', 
#         # change the range of the years from 1980 to currentYear - 5
#         widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
#     )
    
#     def __init__(self, *args, **kwargs):
#         super(FriendForm, self).__init__(*args, **kwargs)
#         ## add a "form-control" class to each form input
#         ## for enabling bootstrap
#         for name in self.fields.keys():
#             self.fields[name].widget.attrs.update({
#                 'class': 'form-control',
#             })

#     class Meta:
#         model = Friend
#         fields = ("__all__")


class FriendForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(FriendForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Friend
        fields = ("__all__")

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .filters import ProductFilter
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import JsonResponse
from django.core import serializers
from .forms import FriendForm
from .models import Friend, Product

from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseNotFound

from django.views import View

class Home(ListView):
    model = Product
    template_name = 'products/home.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ProductFilter(self.request.GET, queryset=self.get_queryset())
        return context

def home(request):
    product_list = Product.objects.all()
    product_filter = ProductFilter(request.GET, queryset=product_list)
    return render(request, 'products/home.html', {'filter': product_filter})

class ProductDetail(LoginRequiredMixin, DetailView):
	model = Product



def postFriend(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        # get the form data
        form = FriendForm(request.POST)
        # save the data and after fetch the object in instance
        if form.is_valid():
            instance = form.save()
            # serialize in new friend object in json
            ser_instance = serializers.serialize('json', [ instance, ])
            # send to client side.
            return JsonResponse({"instance": ser_instance}, status=200)
        else:
            # some form errors occured.
            return JsonResponse({"error": form.errors}, status=400)

    # some error occured
    return JsonResponse({"error": ""}, status=400)



def checkNickName(request):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        nick_name = request.GET.get("nick_name", None)
        # check for the nick name in the database.
        if Friend.objects.filter(nick_name = nick_name).exists():
            # if nick_name found return not valid new friend
            return JsonResponse({"valid":False}, status = 200)
        else:
            # if nick_name not found, then user can create a new friend.
            return JsonResponse({"valid":True}, status = 200)

    return JsonResponse({}, status = 400)




def indexView(request, slug):
    form = FriendForm()
    friends = Friend.objects.all()


    
    # Для примера берем первый объект модели Product
    # object = Product.objects.first()

    # object = Product.objects.get(slug = slug)

    try:
        product = Product.objects.get(slug = slug)
    except ObjectDoesNotExist:
        product = None
        # return HttpResponseNotFound("<h2>Not Found</h2>")
        # return JsonResponse(status=404, data={'status':'false','message':"Object Does Not Exist"})

    # return render(request, "product/<slug>/", {"form": form, "friends": friends})
    return render(request, "products/product_detail.html", {"form": form, "friends": friends, "object": product})



def postFriend(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        # get the form data
        form = FriendForm(request.POST)
        # save the data and after fetch the object in instance
        if form.is_valid():
            instance = form.save()
            # serialize in new friend object in json
            ser_instance = serializers.serialize('json', [ instance, ])
            # send to client side.
            return JsonResponse({"instance": ser_instance}, status=200)
        else:
            # some form errors occured.
            return JsonResponse({"error": form.errors}, status=400)

    # some error occured
    return JsonResponse({"error": ""}, status=400)



class FriendView(View):
    form_class = FriendForm
    template_name = "products/product_detail.html"

    def get(self, *args, **kwargs):
        form = self.form_class()
        friends = Friend.objects.all()
        return render(self.request, self.template_name, 
            {"form": form, "friends": friends})

    def post(self, *args, **kwargs):
        # request should be ajax and method should be POST.
        if self.request.is_ajax and self.request.method == "POST":
            # get the form data
            form = self.form_class(self.request.POST)
            # save the data and after fetch the object in instance
            if form.is_valid():
                instance = form.save()
                # serialize in new friend object in json
                ser_instance = serializers.serialize('json', [ instance, ])
                # send to client side.
                return JsonResponse({"instance": ser_instance}, status=200)
            else:
                # some form errors occured.
                return JsonResponse({"error": form.errors}, status=400)

        # some error occured
        return JsonResponse({"error": ""}, status=400)
	

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}
    {% endblock style %}
  </head>




<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>005.ru</title>
  <style>
  	.card{
  		    height: 350px;
  	}
  	.card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden; }
  .card-product .price-new, .card-product .price {
    margin-right: 5px; }
  .card-product .price-old {
    color: #999; }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center; }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover; }
      
      .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px; }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .title {
    margin-top: 0; }
  </style>
</head>
<body>
{% include 'products/navbar.html' %}


    {% if messages %}
    <div class="messages container mt-2">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
  {% endif %}
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>







</html>
<script>
  
</script>
</body>
</html>

products/templates/products/home.html
{% extends 'products/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <div class="container my-5">
  	<!--  <h2 class="my-5">Продукты</h2> -->

    <div class="col-md-3">
         <form method="get">
            {{ filter.form| crispy }}
            <button type="submit">Поиск</button>
        </form>
    </div>
    <div class="col-md-9">
		<div class="row">
			{% for product in filter.qs %}
		  <div class="col-md-6 col-sm-12 col-lg-4">
			<figure class="card card-product">
				<div class="img-wrap"> 
					<img src="media/{{ product.mainimage }}" style="width: 100%; height: 200px;">
				</div>
				<figcaption class="info-wrap">
					<h6 class="title text-dots"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
					
					<div class="action-wrap">
						<!-- <a href="cart/{{ product.slug }}" class="btn btn-primary btn-sm"> Add to Cart </a>
            			<a href="cart/" class="btn btn-primary btn-sm"> View Cart </a> -->
<!--             <a href="remove/{{ product.slug }}" class="btn btn-danger btn-sm"> Remove</a>
 -->						<!-- price-wrap.// -->
						 <div class="price-wrap h5">
						<!--	<span class="price-new">руб. {{product.price}}</span> -->
						<!--   	<del class="price-old">руб. 1980</del> -->
						</div> 
					</div> <!-- action-wrap -->
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col // -->
      {% endfor %}
		</div>
	</div>
  </div>
  </div>
{% endblock %}

products/templates/products/navbar.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="/">Django Ecommerce Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li {% if request.path == 'contact' %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
        <a class="nav-link" href="#">Men <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Women</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Electronics</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="#">Electronics</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
          <i class="fa fa-shopping-cart"></i> Cart
          <span class="badge badge-light">{{ request.user| cart_total }}</span>
        </a>
      </li>
       <li class="nav-item">
        
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-tie"></i> {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Dashboard</a>
          <a class="dropdown-item" href="{% url 'checkout:oderView' %}">Orders</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </li>
      {% else %}
       <li class="nav-item">
        <a  class="btn btn-primary" href="/accounts/login/">Login / Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>

products/templates/products/product_detail.html
{% extends 'products/base.html' %}


{% block content %}

<div class="container my-5">
    
<div class="card">
    <div class="row">
        <aside class="col-sm-5 border-right">
<article class="gallery-wrap"> 
<div class="img-big-wrap">
  <div> <a href="#"><img src="/media/{{ object.mainimage }}" style="width: 450px"></a></div>
</div> <!-- slider-product.// -->
</article> <!-- gallery-wrap .end// -->
        </aside>
        <aside class="col-sm-7">
<article class="card-body p-5">
    <h3 class="title mb-3">{{ object.name }}</h3>
<p class="price-detail-wrap"> 
    <span class="price h3 text-warning"> 
        <span class="currency">US $</span><span class="num">{{ object.price }}</span>
    </span> 
    
</p> <!-- price-detail-wrap .// -->
<dl class="item-property">
  <dt>Description</dt>
  <dd><p>{{ object.preview_text }}</p></dd>
</dl>

    <a href="{% url 'mainapp:cart' object.slug %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to cart </a>
</article> <!-- card-body.// -->
        </aside> <!-- col.// -->
    </div> <!-- row.// -->
</div> <!-- card.// -->


<div class="container-fluid">
    <form id="friend-form">
        <div class="row">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group col-4">
                <label class="col-12">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            
            <div class = "col text-center">
                <input type="submit" class="btn btn-primary" value="Цена" />
            </div>

        </div>
    <form>
</div>

<hr />

<div class="container-fluid">
    <table class="table table-striped table-sm" id="my_friends">
        <thead>
            <tr>
               
                <th>First name</th>
                <th>Tirazh</th>
                <th>DOB</th>
             
            </tr>
        </thead>
        <tbody>
        {% for friend in friends %}
        <tr>
           
            <td>{{friend.first_name}}</td>
            <td>{{friend.tirazh}}</td>
            <td>{{friend.dob | date:"Y-m-d"}}</td>
          
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}



</div>
<!--container.//-->
<div class="container-fluid">
    <form id="friend-form">
        <div class="row">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group col-4">
                <label class="col-12">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            
            <div class = "col text-center">
                <input type="submit" class="btn btn-primary" value="Цена" />
            </div>

        </div>
    <form>
</div>

<hr />












{% block javascript %}
<script>
    $(document).ready(function () {
        /*
            On submiting the form, send the POST ajax
            request to server and after successfull submission
            display the object.
        */
        $("#friend-form").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            var serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'post_friend' %}",
                data: serializedData,
                success: function (response) {
                    // on successfull creating object
                    // 1. clear the form.
                    $("#friend-form").trigger('reset');
                    // 2. focus to nickname input 
                    $("#id_nick_name").focus();

                    // display the newly friend to table.
                    var instance = JSON.parse(response["instance"]);
                    var fields = instance[0]["fields"];
                    $("#my_friends tbody").prepend(
                        `<tr>
                        <td>${fields["nick_name"]||""}</td>
                        <td>${fields["first_name"]||""}</td>
                        <td>${fields["last_name"]||""}</td>
                        <td>${fields["likes"]||""}</td>
                        <td>${fields["dob"]||""}</td>
                        <td>${fields["lives_in"]||""}</td>
                        </tr>`
                    )
                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        })

        /*
        On focus out on input nickname,
        call AJAX get request to check if the nickName
        already exists or not.
        */
        $("#id_nick_name").focusout(function (e) {
            e.preventDefault();
            // get the nickname
            var nick_name = $(this).val();
            // GET AJAX request
            $.ajax({
                type: 'GET',
                url: "{% url 'validate_nickname' %}",
                data: {"nick_name": nick_name},
                success: function (response) {
                    // if not valid user, alert the user
                    if(!response["valid"]){
                        alert("You cannot create a friend with same nick name");
                        var nickName = $("#id_nick_name");
                        nickName.val("")
                        nickName.focus()
                    }
                },
                error: function (response) {
                    console.log(response)
                }
            })
        })
    })
</script>
{% endblock javascript %}